# Generated by Django 2.2.1 on 2019-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_db',
            },
        ),
        migrations.CreateModel(
            name='JingDongScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('property', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'jd_db',
            },
        ),
        migrations.CreateModel(
            name='TmallScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tm_db',
            },
        ),
        migrations.CreateModel(
            name='TuhuScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'th_db',
            },
        ),
        migrations.CreateModel(
            name='TuhuTireScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('specifications', models.CharField(max_length=255)),
                ('speed_level', models.CharField(max_length=255)),
                ('load_index', models.CharField(max_length=255)),
                ('tire_category', models.CharField(max_length=255)),
                ('tire_pattern', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('evaluate_count', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tuhu_tire_db',
            },
        ),
    ]
