# Generated by Django 2.2.1 on 2019-06-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jingdongscrapy_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='jingdongscrapy',
            name='href2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
